id: P936384FA
initial_creation_type: input
source_metadata:
  title: Acrostic Series
  language: fr
  description: 'A series of acrostic or abecedarian forms of poetry and composition,
    known in Tibetan as katsom (ka rtsom):'
  volume:
    97c572958a534bf7878afaadf50f7043:
      title: Khandro's Plea
      parent: Advice
    7d8521ecf8f34e1a818c511f269feac0:
      title: 'A Blossoming of the Intellect: In Praise of the Great Pioneer Thönmi
        Sambhoṭa'
      parent: Praise
    fbf2db3d74db464da8893b2c4462b930:
      title: 'A Surge of Faith: Verses In Praise of Tārā'
      parent: Praise
    9c7c689e775e420eb0bd5acd5fc1a758:
      title: Acrostic Song
      parent: Songs
created_at: '2022-03-01T02:30:30.465045'
last_modified_at: '2022-03-01T02:30:30.465048'
